version: "3"

services:
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WP_VERSION: "6.0"
        WP_CLI_VERSION: "2"
        PHP_VERSION: "8"
        UID: ${UID}
        GID: ${GID}
    ports:
      - "8000:80"
    restart: always
    volumes:
      - html:/var/www/html
      - ../wp-content/languages:/var/www/html/wp-content/languages
      - ../wp-content/plugins:/var/www/html/wp-content/plugins
      - ../wp-content/themes/default:/var/www/html/wp-content/themes/default
      - ..:/workspace
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
volumes:
  db_data:
  html:
